### ISSUE TITLE
[BUG] NoSuchMethodError: AssistantMessage.<init> incompatible with Spring AI 1.1.0

### ISSUE THREAD

**Issue by zhhnb123** [alibaba/spring-ai-alibaba#3180]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When using spring-ai-alibaba with Spring AI 1.1.0, calling DashScopeChatModel(1.1.0.0-M5) triggers a runtime exception:
java.lang.NoSuchMethodError:
'void org.springframework.ai.chat.messages.AssistantMessage.<init>(java.lang.String, java.util.Map, java.util.List)'
This indicates that spring-ai-alibaba is still depending on the old constructor of AssistantMessage, which was changed in Spring AI 1.1.x.

### Expected Behavior

spring-ai-alibaba should be compatible with Spring AI 1.1.x, or provide a version matrix telling users which versions are compatible.

### Environment

```markdown
Spring AI Alibaba version(s):1.1.0.0-M5
```

**Comment by ownoi** [comment]
I also tried upgrading my Spring AI version. I upgraded to M4 and Alibaba AI M5, and the problem was solved.

```
        <spring-ai.version>1.1.0-M4</spring-ai.version>
        <alibaba-ai.version>1.1.0.0-M5</alibaba-ai.version>
```

**Comment by guanxuc** [comment]
has fixed with https://github.com/alibaba/spring-ai-alibaba/pull/3073

**Comment by chickenlj** [comment]
We are still working on the 1.1.0 adaption, expected to be released soon.

**Comment by csjbebetter** [comment]
> We are still working on the 1.1.0 adaption, expected to be released soon.

等待适配spring ai 1.1.0版本的spring ai alibaba 。想请假一个问题，方案一：子智能体作为tool；方案二：子智能体作为SubAgentInterceptor；这两个方案有什么不同呢？方案二从package com.alibaba.cloud.ai.graph.agent.extension.interceptor，方案一是官方文档提出的。
